[project]
name = "eap-skills"
version = "1.0.0"
description = "eap-skills"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "defusedxml>=0.7.1",
  "lxml>=5.0.0",
  "Pillow>=10.0.0",
  "markitdown[pptx]>=0.1.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.uv]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[tool.uv.pip]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
